mode: time_layer        # or communication_layer
write_to_csv: true

time_layer:
  num_round: 5

rabbit:
  queue_device_1: "device1"
  queue_device_2: "device2"
  address: "192.168.101.91"
  username: "dai"
  password: "dai"
  virtual_host: "/"
