mode: communication_times        # or layer_times or communication_times
model: "yolo11n.pt"
write_to_csv: true

time_layer:
  num_round: 5
  input_shape: [1, 3, 640, 640]

rabbit:
  queue_device_1: "device1"
  queue_device_2: "device2"
  address: "192.168.101.91"
  username: "dai"
  password: "dai"
  virtual_host: "/"
